use releaser 1.1.0

diff --git a/test/integration/test-files/docker-private-complex/tasks b/test/integration/test-files/docker-private-complex/tasks
--- a/test/integration/test-files/docker-private-complex/tasks
+++ b/test/integration/test-files/docker-private-complex/tasks
@@ -2,17 +2,13 @@
 
 set -e
 if [[ ! -f ./releaser ]]; then
-  wget --quiet http://http.archive.ai-traders.com/releaser/1.0.8/releaser || { echo "Cannot download releaser, ignoring."; }
+  wget --quiet http://http.archive.ai-traders.com/releaser/1.1.0/releaser || { echo "Cannot download releaser, ignoring."; }
 fi
 if [[ -f ./releaser ]]; then
   source ./releaser
 fi
 docker_ops=$(readlink -f ../../../../src/docker-ops)
 source ${docker_ops}
-if [[ -f ./releaser ]]; then
-  # This goes as last in order to let end user variables override default values
-  releaser_init
-fi
 
 image_dir1="./image1"
 imagerc_filename1="imagerc1"
@@ -62,23 +58,23 @@ case "${command}" in
       if [[ -n "$2" ]]; then
         next_version="$2"
       else
-        version=$(get_last_version_from_changelog "${changelog_file}")
-        next_version=$(bump_patch_version "${version}")
+        version=$(releaser::get_last_version_from_whole_changelog "${changelog_file}")
+        next_version=$(releaser::bump_patch_version "${version}")
       fi
-      set_version_in_changelog "${changelog_file}" "${next_version}"
+      releaser::set_version_in_changelog "${changelog_file}" "${next_version}"
       exit $?
       ;;
   verify_version)
-      verify_changelog_version
+      releaser::verify_changelog_version
       exit $?
       ;;
   release)
       ./tasks verify_version
-      version=$(get_last_version_from_changelog "${changelog_file}")
+      version=$(releaser::get_last_version_from_whole_changelog "${changelog_file}")
       git tag "${version}" && git push origin "${version}"
       ;;
   publish)
-      version=$(get_last_version_from_changelog "${changelog_file}")
+      version=$(releaser::get_last_version_from_whole_changelog "${changelog_file}")
       # push production image1 to image_registry1
       docker_ops::push_production "${image_dir1}"  "${imagerc_filename1}" "${image_name1}" "${version}" "${image_registry1}"
       # push production image2 to image_registry2
diff --git a/test/integration/test-files/docker-public/tasks b/test/integration/test-files/docker-public/tasks
--- a/test/integration/test-files/docker-public/tasks
+++ b/test/integration/test-files/docker-public/tasks
@@ -2,7 +2,7 @@
 
 set -e
 if [[ ! -f ./releaser ]]; then
-  wget --quiet http://http.archive.ai-traders.com/releaser/1.0.8/releaser || { echo "Cannot download releaser, ignoring."; }
+  wget --quiet http://http.archive.ai-traders.com/releaser/1.1.0/releaser || { echo "Cannot download releaser, ignoring."; }
 fi
 if [[ -f ./releaser ]]; then
   source ./releaser
@@ -47,14 +47,14 @@ case "${command}" in
       if [[ -n "$2" ]]; then
         next_version="$2"
       else
-        version=$(get_last_version_from_changelog "${changelog_file}")
-        next_version=$(bump_patch_version "${version}")
+        version=$(releaser::get_last_version_from_whole_changelog "${changelog_file}")
+        next_version=$(releaser::bump_patch_version "${version}")
       fi
-      set_version_in_changelog "${changelog_file}" "${next_version}"
+      releaser::set_version_in_changelog "${changelog_file}" "${next_version}"
       exit $?
       ;;
   verify_version)
-      verify_changelog_version
+      releaser::verify_changelog_version
       exit $?
       ;;
   build)
@@ -75,11 +75,11 @@ case "${command}" in
       ;;
   release)
       ./tasks verify_version
-      version=$(get_last_version_from_changelog "${changelog_file}")
+      version=$(releaser::get_last_version_from_whole_changelog "${changelog_file}")
       git tag "${version}" && git push origin "${version}"
       ;;
   publish)
-      version=$(get_last_version_from_changelog "${changelog_file}")
+      version=$(releaser::get_last_version_from_whole_changelog "${changelog_file}")
       docker_ops::push_production "${image_dir}"  "${imagerc_filename}" "${image_name}" "${version}" "${image_registry}"
       exit $?
       ;;
