Safer loading of releaser and docker-ops

diff --git a/tasks b/tasks
--- a/tasks
+++ b/tasks
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 if [[ ! -f ./releaser ]];then
-  wget http://gogs.ai-traders.com/platform/releaser/raw/0.2.1/src/releaser
+  wget http://gogs.ai-traders.com/platform/releaser/raw/0.2.1/src/releaser || { echo "failed to wget releaser"; exit 1; }
 fi
 source ./releaser
 releaser_init
