fix logging functions' names to be unique

diff --git a/src/docker-ops b/src/docker-ops
--- a/src/docker-ops
+++ b/src/docker-ops
@@ -9,30 +9,30 @@
 # bash completion results in exit too.
 ################################################################################
 
-program_name() {
+docker_ops::program_name() {
   echo "DOCKER-OPS"
 }
-log_debug() {
+docker_ops::log_debug() {
   if [ "${RELEASER_LOG_LEVEL}" == "debug" ]; then
-    echo -e "$(date "+%d-%m-%Y %T") $(program_name) debug: ${1}" >&2
+    echo -e "$(date "+%d-%m-%Y %T") $(docker_ops::program_name) debug: ${1}" >&2
   fi
 }
-log_info() {
-  echo -e "$(date "+%d-%m-%Y %T") $(program_name) info: ${1}" >&2
+docker_ops::log_info() {
+  echo -e "$(date "+%d-%m-%Y %T") $(docker_ops::program_name) info: ${1}" >&2
 }
-log_error() {
-  echo -e "\e[31m$(date "+%d-%m-%Y %T") $(program_name) error: $1\e[0m" >&2
-  echo -e "\e[31m$(date "+%d-%m-%Y %T") $(program_name) error: File: ${BASH_SOURCE[0]}\e[0m" >&2
-  echo -e "\e[31m$(date "+%d-%m-%Y %T") $(program_name) error: Line numbers: ${BASH_LINENO[*]}\e[0m" >&2
+docker_ops::log_error() {
+  echo -e "\e[31m$(date "+%d-%m-%Y %T") $(docker_ops::program_name) error: $1\e[0m" >&2
+  echo -e "\e[31m$(date "+%d-%m-%Y %T") $(docker_ops::program_name) error: File: ${BASH_SOURCE[0]}\e[0m" >&2
+  echo -e "\e[31m$(date "+%d-%m-%Y %T") $(docker_ops::program_name) error: Line numbers: ${BASH_LINENO[*]}\e[0m" >&2
 }
-log_warn() {
-  echo -e "\e[33m$(date "+%d-%m-%Y %T") $(program_name) warn: $1\e[0m" >&2
+docker_ops::log_warn() {
+  echo -e "\e[33m$(date "+%d-%m-%Y %T") $(docker_ops::program_name) warn: $1\e[0m" >&2
 }
 
 # In order to load all the docker-ops functions once you can run:
 # docker_ops || eval "$(curl http://archive.ai-traders.com/docker-ops/0.1.3/docker-ops)"
 # Or you can simply wget that file and source it.
-function docker_ops_loaded {
+function docker_ops::loaded {
   return 0
 }
 
@@ -43,27 +43,27 @@ function docker_build {
   image_tag="$4"
 
   if [[ -z "${image_dir}" ]];then
-    log_error "image_dir not set"
+    docker_ops::log_error "image_dir not set"
     return 1
   fi
-  log_info "image_dir set to: ${image_dir}"
+  docker_ops::log_info "image_dir set to: ${image_dir}"
   if [[ -z "${image_name}" ]];then
-    log_error "image_name not set"
+    docker_ops::log_error "image_name not set"
     return 1
   fi
-  log_info "image_name set to: ${image_name}"
+  docker_ops::log_info "image_name set to: ${image_name}"
   if [[ -z "${imagerc_filename}" ]];then
-    log_error "imagerc_filename not set"
+    docker_ops::log_error "imagerc_filename not set"
     return 1
   fi
-  log_info "imagerc_filename set to: ${imagerc_filename}"
+  docker_ops::log_info "imagerc_filename set to: ${imagerc_filename}"
   initial_dir="$(pwd)"
   cd "${image_dir}"
   if [[ -z "${image_tag}" ]];then
     # set to the latest git commit hash
     image_tag=$(git rev-parse HEAD)
   fi
-  log_info "image_tag set to: ${image_tag}"
+  docker_ops::log_info "image_tag set to: ${image_tag}"
 
   set -x -e
   docker build ${docker_build_options} -t "${image_name}:${image_tag}" .
@@ -89,11 +89,11 @@ function source_imagerc {
   imagerc_filename="$2"
 
   if [[ -z "${image_dir}" ]];then
-    log_error "image_dir not set"
+    docker_ops::log_error "image_dir not set"
     return 1
   fi
   if [[ -z "${imagerc_filename}" ]];then
-    log_error "imagerc_filename not set"
+    docker_ops::log_error "imagerc_filename not set"
     return 1
   fi
   set -x -e
@@ -114,20 +114,20 @@ function docker_push {
   production_image_tag="$3"
 
   if [[ -z "${image_name}" ]];then
-    log_error "image_name not set"
+    docker_ops::log_error "image_name not set"
     return 1
   fi
-  log_info "image_name set to: ${image_name}"
+  docker_ops::log_info "image_name set to: ${image_name}"
   if [[ -z "${testing_image_tag}" ]];then
-    log_error "testing_image_tag not set"
+    docker_ops::log_error "testing_image_tag not set"
     return 1
   fi
-  log_info "testing_image_tag set to: ${testing_image_tag}"
+  docker_ops::log_info "testing_image_tag set to: ${testing_image_tag}"
   if [[ -z "${production_image_tag}" ]];then
-    log_error "production_image_tag not set"
+    docker_ops::log_error "production_image_tag not set"
     return 1
   fi
-  log_info "production_image_tag set to: ${production_image_tag}"
+  docker_ops::log_info "production_image_tag set to: ${production_image_tag}"
   if ! docker images ${image_name} | awk '{print $2}' | grep ${testing_image_tag} 1>/dev/null ; then
     # if docker image does not exist locally, then "docker tag" will fail,
     # so pull it. However, do not always pull it, the image may be not pushed
